class IPlatErrorCode:
    ILLEGAL_PACKET = 0x0F

    DEVICE_IS_NOT_FOUND = 0x10

    SENSOR1_IS_NOT_FOUND = 0x20
    SENSOR2_IS_NOT_FOUND = 0x21
    SENSOR3_IS_NOT_FOUND = 0x22

    SENSOR_IS_NOT_FOUND = [
        SENSOR1_IS_NOT_FOUND,
        SENSOR2_IS_NOT_FOUND,
        SENSOR3_IS_NOT_FOUND
    ]