export const CODE = {
    STATUS_SUCCESS :  true,
    STATUS_FAILED :  false,

    SESSION_SUCCESS : 200,
    SESSION_FAILED : 201,

    LOGIN_SUCCESS :  1000,
    LOGIN_NOT_EXISTED :  1001,
    LOGIN_NOT_MATCH :  1002,

    REGISTER_SUCCESS : 3000,
    ALREADY_USER_IS_EXISTED : 3001,

    REGISTER_DEVICE_SUCCESS : 4000,
    ALREADY_DEVICE_IS_EXISTED : 4001,

    REGISTER_SENSOR_SUCCESS : 4100,
    ALREADY_SENSOR_IS_EXISTED : 4001,
}

/*
STATUS_SUCCESS = True
STATUS_FAILED = False

# DB STATE
DB_CODE_SUCCESS = 0
DB_CODE_FAILED = 100

# LOGIN
CODE_LOGIN_SUCCESS = 1000
CODE_LOGIN_NOT_EXISTED = 1001
CODE_LOGIN_NOT_MATCH = 1002

# LOGOUT
CODE_LOGOUT_SUCCESS = 2000

# REGISTER
CODE_REGISTER_SUCCESS = 3000
CODE_ALREADY_USER_IS_EXISTED = 3001

 */
